"""added some fields to transactions

Revision ID: 0101da866703
Revises: 79e083faf2ae
Create Date: 2025-12-13 20:40:54.608765

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel 


# revision identifiers, used by Alembic.
revision: str = '0101da866703'
down_revision: Union[str, Sequence[str], None] = '79e083faf2ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('to_account_id', sa.Uuid(), nullable=True))
    op.add_column('transactions', sa.Column('reference_number', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True))
    op.alter_column('transactions', 'currency_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_index(op.f('ix_transactions_to_account_id'), 'transactions', ['to_account_id'], unique=False)
    op.create_foreign_key(None, 'transactions', 'accounts', ['to_account_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.drop_index(op.f('ix_transactions_to_account_id'), table_name='transactions')
    op.alter_column('transactions', 'currency_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('transactions', 'reference_number')
    op.drop_column('transactions', 'to_account_id')
    # ### end Alembic commands ###
