"""added auth_session, security_event, user_device table1

Revision ID: 268424f902f1
Revises: 2f62ce13c6cd
Create Date: 2025-12-31 23:54:09.883278

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel 


# revision identifiers, used by Alembic.
revision: str = '268424f902f1'
down_revision: Union[str, Sequence[str], None] = '2f62ce13c6cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
