"""account name unique

Revision ID: 2f12b009ee87
Revises: f514e21ab410
Create Date: 2025-12-26 18:09:09.917449

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel 
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2f12b009ee87'
down_revision: Union[str, Sequence[str], None] = 'f514e21ab410'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('accounts', 'name',
               existing_type=sa.VARCHAR(length=20),
               type_=sqlmodel.sql.sqltypes.AutoString(length=50),
               existing_nullable=False)
    op.drop_index(op.f('ix_accounts_name'), table_name='accounts')
    op.create_index(op.f('ix_accounts_name'), 'accounts', ['name'], unique=True)
    op.alter_column('audit_logs', 'timestamp',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.drop_index(op.f('ix_recurring_transactions_transaction_id'), table_name='recurring_transactions')
    op.create_index(op.f('ix_recurring_transactions_transaction_id'), 'recurring_transactions', ['transaction_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_recurring_transactions_transaction_id'), table_name='recurring_transactions')
    op.create_index(op.f('ix_recurring_transactions_transaction_id'), 'recurring_transactions', ['transaction_id'], unique=False)
    op.alter_column('audit_logs', 'timestamp',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.drop_index(op.f('ix_accounts_name'), table_name='accounts')
    op.create_index(op.f('ix_accounts_name'), 'accounts', ['name'], unique=False)
    op.alter_column('accounts', 'name',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    # ### end Alembic commands ###
