"""added auth_session, security_event, user_device table

Revision ID: 493a2c6fded4
Revises: bfebc44d18b3
Create Date: 2025-12-31 20:16:01.536922

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel 


# revision identifiers, used by Alembic.
revision: str = '493a2c6fded4'
down_revision: Union[str, Sequence[str], None] = 'bfebc44d18b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
