"""added status_code to auditlog

Revision ID: 79e083faf2ae
Revises: 756a0960afe5
Create Date: 2025-12-13 18:05:45.471699

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel 


# revision identifiers, used by Alembic.
revision: str = '79e083faf2ae'
down_revision: Union[str, Sequence[str], None] = '756a0960afe5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audit_logs', sa.Column('status_code', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('audit_logs', 'status_code')
    # ### end Alembic commands ###
