"""fixed currency

Revision ID: c9b53eb99e26
Revises: ccfd2ae7888d
Create Date: 2025-12-11 06:32:02.593387

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel 
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c9b53eb99e26'
down_revision: Union[str, Sequence[str], None] = 'ccfd2ae7888d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('currencies', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.drop_column('currencies', 'ccreated_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('currencies', sa.Column('ccreated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_column('currencies', 'created_at')
    # ### end Alembic commands ###
